BARC UAT/src/objects/Address_Master__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town / Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address Master</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>Address_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Master</label>
        <referenceTo>Address_Master__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Code__c</fullName>
        <label>LCO Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Cluster Items</relationshipLabel>
        <relationshipName>Cluster_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STB_ID__c</fullName>
        <label>STB ID/ GOS STB ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card_ID__c</fullName>
        <label>Smart Card ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_No__c</fullName>
        <label>VC No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Sr No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Local_Operator__c.object
<CustomObject>
    <fields>
        <fullName>LCO_Partner_Pincode__c</fullName>
        <label>LCO / Partner Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipName>Local_Operators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner / Local Operator</label>
    <nameField>
        <label>LCO / Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner / Local Operators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Operator__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Operator</label>
    <nameField>
        <label>Operator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Sampling__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Code__c</fullName>
        <label>LCO Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Name__c</fullName>
        <label>LCO Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator_Name__c</fullName>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card__c</fullName>
        <label>Smart Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StbID__c</fullName>
        <label>STBID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_No__c</fullName>
        <label>VC No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sampling</label>
    <nameField>
        <label>Sampling No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Samplings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/GenerateClusterBatch.cls
global class GenerateClusterBatch implements Database.Batchable<sObject> {
    global String samplingNo{get;set;}
    global GenerateClusterBatch(String smNo){
        samplingNo = smNo;
    }
     
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('samplingNo ===='+samplingNo);
        String query = ' SELECT  Id,  Name,  StbID__c,District__c,  Smart_Card__c, VC_No__c, STB_Type__c,  Status__c,Operator_Name__c,LCO_Name__c,  Cluster__c,  State__c,  City__c,  Town_Village__c,  Pincode__c,  LCO_Code__c FROM Sampling__c WHERE Name=: samplingNo' ;                
        return Database.getQueryLocator(query);     
    }
     
    global void execute(Database.BatchableContext BC, List<Sampling__c> sampList){        
        System.debug('sampList ===='+sampList);
        Set<String> clusterSet = new Set<String>();
        for(Sampling__c samp : sampList){          
            clusterSet.add(samp.Name);   
        } 
        
        List<Cluster__c> exCluList = [SELECT Id,Name FROM Cluster__c WHERE Name in: clusterSet];
        Map<String,String> exClMap = new Map<String,String>();
        for(Cluster__c clu: exCluList){
            exClMap.put(clu.Name,clu.Id);
        }
        
        List<Address_Master__c> addressMaster = [ SELECT  Id,  Name FROM Address_Master__c];
        Map<String,String> adMap = new Map<String,String>();
        for(Address_Master__c am: addressMaster){
            adMap.put(am.Name,am.Id);
        }
        
        List<Local_Operator__c> localOperatorList = [SELECT Id, Name,LCO_Partner_Pincode__c FROM Local_Operator__c];
        Map < String, String > lopMap = new Map < String, String > ();
        Map<String,String> lcoMap = new Map<String,String>();
        for (Local_Operator__c o: localOperatorList) {
            String key = o.Name+o.LCO_Partner_Pincode__c;
            System.debug('keyM ===='+key);
            lopMap.put(key, o.Id);
            lcoMap.put(o.Name,o.Id);
        }
        
        List<Operator__c> opTechList = [SELECT Id,Name FROM Operator__c];
        Map<String,String> techMap = new Map<String,String>();
        for (Operator__c o: opTechList) {
            techMap.put(o.Name, o.Id);
        }
        
        List<Cluster_Item__c> NclusterItemList = new List<Cluster_Item__c>();
        for(Sampling__c samp : sampList){ 
            
            Cluster__c cl = new Cluster__c();
             System.debug('samp ===='+samp);
            if(exClMap.get(samp.Cluster__c) == null){
                cl.Name = samp.Cluster__c;
                cl.Town_Village__c = samp.Town_Village__c;
                cl.City__c = samp.City__c;
                String key = samp.LCO_Name__c+samp.Pincode__c;
                System.debug('key ===='+key);
                if(lopMap.get(key) != null){
                    cl.Local_Operator__c = lopMap.get(key);
                }else if(lcoMap.get(samp.LCO_Name__c) != null){
                    cl.Local_Operator__c = lcoMap.get(samp.LCO_Name__c);
                }
                
                if(techMap.get(samp.Operator_Name__c) != null){
                    cl.Operator__c = techMap.get(samp.Operator_Name__c);
                }
                
                cl.State__c = samp.State__c;
                cl.Pincode__c = samp.Pincode__c;
                cl.Sampling__c = samp.Id;
                cl.District__c = samp.District__c;
                if(adMap.get(samp.Pincode__c) != null){
                    cl.Address_Master__c = adMap.get(samp.Pincode__c);
                }
                insert cl;
                
                exClMap.put(cl.Name, cl.Id);
            }else{
                cl.Id = exClMap.get(samp.Cluster__c);
            }
            
            
            Cluster_Item__c cli = new Cluster_Item__c();
            cli.Smart_Card_ID__c = samp.Smart_Card__c;
            cli.STB_ID__c = samp.StbID__c;
            cli.STB_Type__c = samp.STB_Type__c;
            cli.VC_No__c = samp.VC_No__c;
            cli.Cluster__c = cl.Id;
            NclusterItemList.add(cli);
        }
        System.debug('NclusterItemList ======'+NclusterItemList);
        insert NclusterItemList;
        
        
    }
     
    global void finish(Database.BatchableContext BC) {
         
    }
}