BARC UAT/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head_end__c</fullName>
        <label>Head end</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Cluster Items</relationshipLabel>
        <relationshipName>Cluster_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card_ID__c</fullName>
        <label>Smart Card ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Sr No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Sampling__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card__c</fullName>
        <label>Smart Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StbID__c</fullName>
        <label>STBID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sampling</label>
    <nameField>
        <label>Sampling No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Samplings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Name__c</fullName>
        <label>District Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Durables_in_working_condition__c</fullName>
        <inlineHelpText>Please select the durables which are in working condition, at your residence (Select Multiple option)</inlineHelpText>
        <label>Durables in working condition</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Air Conditioner</fullName>
                </value>
                <value>
                    <fullName>Car / Jeep / Van</fullName>
                </value>
                <value>
                    <fullName>Celling Fan</fullName>
                </value>
                <value>
                    <fullName>Color Tv</fullName>
                </value>
                <value>
                    <fullName>LPG Stove</fullName>
                </value>
                <value>
                    <fullName>Personal Computer/ Laptop</fullName>
                </value>
                <value>
                    <fullName>Refrigerator</fullName>
                </value>
                <value>
                    <fullName>Two-Wheeler</fullName>
                </value>
                <value>
                    <fullName>Washing Machine</fullName>
                </value>
                <value>
                    <fullName>Does the Chief wage earner (contributes the most to household expenditure) of the Household own any agricultural land?</fullName>
                </value>
                <value>
                    <fullName>Car/Jeep/Van</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Head_end__c</fullName>
        <label>Head end</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House_Member_Works_in_of_the_Companies__c</fullName>
        <inlineHelpText>Looking at the following list Please tell me whether you or any other household member works for any of the following type of companies: (If administered by Technician else don’t ask)</inlineHelpText>
        <label>House Member Works in of the Companies</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing Research Agency</fullName>
                </value>
                <value>
                    <fullName>Advertising Agency</fullName>
                </value>
                <value>
                    <fullName>Media Company (Print, Television, Radio, Satellite Channels etc.)</fullName>
                </value>
                <value>
                    <fullName>Public Relations Company</fullName>
                </value>
                <value>
                    <fullName>Digital agencies</fullName>
                </value>
                <value>
                    <fullName>Retail shop owner selling DTH, recharging DTH</fullName>
                </value>
                <value>
                    <fullName>Telecom &amp; Internet</fullName>
                </value>
                <value>
                    <fullName>None Of The Above</fullName>
                </value>
                <value>
                    <fullName>Media Company</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household_Status__c</fullName>
        <label>Household Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agreed Scheduled</fullName>
                </value>
                <value>
                    <fullName>Next Call</fullName>
                </value>
                <value>
                    <fullName>Not Connected</fullName>
                </value>
                <value>
                    <fullName>Installed agree</fullName>
                </value>
                <value>
                    <fullName>Next Visit</fullName>
                </value>
                <value>
                    <fullName>Door Locked</fullName>
                </value>
                <value>
                    <fullName>Refuse</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Technical Issue</fullName>
                </value>
                <value>
                    <fullName>Dongle Not Working</fullName>
                </value>
                <value>
                    <fullName>STB Not Working</fullName>
                </value>
                <value>
                    <fullName>Home Not Found</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>FORWARDED</fullName>
                </value>
                <value>
                    <fullName>Agreed/Scheduled</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_household_part_of_TMP__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is your household currently part of a Television Measurement Panel?</inlineHelpText>
        <label>Is household part of TMP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.Pincode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pincode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_ID_GOS_STB_ID__c</fullName>
        <label>STB ID/ GOS STB ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card_ID__c</fullName>
        <label>Smart Card ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Case__r.Cluster__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Television_Measurement_Panel_for_3_mnt__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Were you part of a Television Measurement Panel in the previous three months?</inlineHelpText>
        <label>Television Measurement Panel for 3 mnt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.Town_Village__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Town Village</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Working_TV_sets__c</fullName>
        <inlineHelpText>How many (number of) working TV sets do you have at home?</inlineHelpText>
        <label>Working TV sets</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Would_you_like_to_be_part_of_TMP__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Would you like to be part of a Television Measurement Panel, wherein a dongle would be installed on your Set Top Box to improve our services and acquire critical feedback on any problems faced by our customers?</inlineHelpText>
        <label>Would you like to be part of TMP</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/PushSurveyToAppBatchTest.cls
@isTest
public class PushSurveyToAppBatchTest {
    
    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            if (req.getEndpoint().endsWith('insertOperator')) {
                
                
                Boolean b = True;
                String reCode = '200';
                String fullJson = 'Here is my String JSON';
                String sta = 'OK';
                String Js = '{"data":[{"operator_id":21}],"flag":1,"Msg":"Operator Created Successfully"}';
                
                HttpResponse res = new HttpResponse();
                res.setBody(Js);
                res.setStatusCode(200);
                res.setStatus(sta);
                return res;
                
                
            } else  if (req.getEndpoint().endsWith('insertLCO')) {
                
                String sta = 'OK';
                String js = '{"data":[{"lco_id":65}],"flag":1,"Msg":"Operator Created Successfully"}';
                HTTPResponse res = new HTTPResponse();
                res.setBody(js);
                res.setHeader('Content-Type', 'application/json');
                res.setStatusCode(200);
                res.setStatus(sta);
                return res;
            }
             else  if (req.getEndpoint().endsWith('insertTech')) {
                
                String sta = 'OK';
                String js = '{"data":[{"lco_id":65}],"flag":1,"Msg":"Operator Created Successfully"}';
                HTTPResponse res = new HTTPResponse();
                res.setBody(js);
                res.setHeader('Content-Type', 'application/json');
                res.setStatusCode(200);
                res.setStatus(sta);
                return res;
            }
             else  if (req.getEndpoint().endsWith('insertClusters')) {
                
                String sta = 'OK';
                String js = '{"data":[{"lco_id":65}],"flag":1,"Msg":"Operator Created Successfully"}';
                HTTPResponse res = new HTTPResponse();
                res.setBody(js);
                res.setHeader('Content-Type', 'application/json');
                res.setStatusCode(200);
                res.setStatus(sta);
                return res;
            }
            
            return null;
        }
    }

	public static testMethod void test() {
	    
	    Sampling__c scm = new Sampling__c(
	      Name = '101',                         // Sampling No
          Cluster__c = '55003978',                // Cluster
          STB_Type__c = 'GOSPELL',                // STB Type
          City__c = 'Ernakulam',                  // City
          StbID__c = '4D0038A30',                 // STBID
          State__c = 'RAJASTHAN',                 // State
          Status__c = 'Active',                   // Status
          Town_Village__c = '5 Psd B.O',          // Town Village
          Smart_Card__c = '127867565432',         // Smart Card
          Pincode__c = '110095'                  // Pincode
          ); 
	    insert scm;
	    
	    Cluster__c clus = new Cluster__c(
          Name = '55003973',                                // Cluster No
          Sampling__c = scm.id,                             // Sampling
          City__c = 'Aligarh',                              // City
          Pincode__c = '110012',                            // Pincode
          State__c = 'ANDHRA PRADESH',                      // State
          Town_Village__c = '(Gandhinagar) Sector 22 S.O'   // Town Village
        );
        insert clus;
        
        Cluster_Item__c cli = new Cluster_Item__c(cluster__c=clus.id);
        insert cli;
        
        Case cs = new Case(Cluster__c=clus.id, Sampling__c=scm.id, Status='New', Origin='Email');
        insert cs;
        
        Survey__c sur = new Survey__c(
          Head_end__c = '111111',                                                  // Head end
        //   District_Name__c = 'Bangalore',                                          // District Name
          Smart_Card_ID__c = '109876543212',                                       // Smart Card ID
          STB_ID_GOS_STB_ID__c = '109876543212',                                   // STB ID/ GOS STB ID
          Case__c = cs.id,                                             // Case
          Household_Status__c = 'Agreed Scheduled',                                // Household Status
          House_Member_Works_in_of_the_Companies__c = 'None Of The Above',         // House Member Works in of the Companies
          Durables_in_working_condition__c = 'Air Conditioner; Car / Jeep / Van',  // Durables in working condition
          Working_TV_sets__c = '1',                                                // Working TV sets
          Is_household_part_of_TMP__c = false,                                     // Is household part of TMP
          Would_you_like_to_be_part_of_TMP__c = true,                              // Would you like to be part of TMP
          Television_Measurement_Panel_for_3_mnt__c = false                       // Television Measurement Panel for 3 mnt
        );
        insert sur;
        
        Test.startTest();
	    
	    PushSurveyToAppBatch psa = new PushSurveyToAppBatch('101');
	    
	    Test.setMock(HttpCalloutMock.class, new Mock());
	    Database.executeBatch(psa);
	    Test.stopTest();

	}
	
	static void xyz() {
        Test.setMock(HttpCalloutMock.class, new Mock());
        
    }


}