BARC UAT/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Appointment_End_Date__c</fullName>
        <label>Appointment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Appointment_Start_Date__c</fullName>
        <label>Appointment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Casualty__c</fullName>
        <label>Casualty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date_Time__c</fullName>
        <label>Due Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Early_Start__c</fullName>
        <label>Early Start</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interview_End_Date__c</fullName>
        <label>Interview End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interview_Start_Date__c</fullName>
        <label>Interview Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Late_Start__c</fullName>
        <label>Late Start</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>URN_without_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>URN without Visit</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head_end__c</fullName>
        <label>Head end</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Local_Operator__c.object
<CustomObject>
    <fields>
        <fullName>CAFID__c</fullName>
        <label>CAFID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Partner_Code__c</fullName>
        <label>LCO / Partner Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipName>Local_Operators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner / Local Operator</label>
    <nameField>
        <label>LCO / Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner / Local Operators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Operator__c.object
<CustomObject>
    <fields>
        <fullName>CAFID__c</fullName>
        <label>CAFID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Operator</label>
    <nameField>
        <label>Operator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Sampling__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_No__c</fullName>
        <label>VC No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sampling</label>
    <nameField>
        <label>Sampling No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Samplings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <formula>Case__r.Cluster__r.District__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head_end__c</fullName>
        <label>Head end</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.Pincode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pincode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_ID_GOS_STB_ID__c</fullName>
        <label>STB ID/ GOS STB ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card_ID__c</fullName>
        <label>Smart Card ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Case__r.Cluster__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_District_Name__c</fullName>
        <label>Sub District Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Technician_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician Number</label>
        <referenceTo>Operator_Technician__c</referenceTo>
        <relationshipLabel>Survey</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.Town_Village__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Town Village</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_No__c</fullName>
        <label>VC No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/PushSurveyToAppBatch.cls
global class PushSurveyToAppBatch implements Database.Batchable<sObject>, Database.AllowsCallouts,Database.Stateful {

global String samplingNo{get;set;}
    
    global PushSurveyToAppBatch(String smNo){
        samplingNo = smNo;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = ' SELECT  Id,  CaseNumber,  ContactId,  AccountId,Cluster__r.District__c,  ParentId,  Type,  Status,  Reason,  Origin,  Subject,  Priority,  Description,  Appointment_Start_Date__c, Appointment_End_Date__c,  Early_Start__c,  Late_Start__c,  Due_Date_Time__c,  Start_Date_Time__c,  End_Date_Time__c,  Casualty__c,  Interview_Start_Date__c,  URN_without_Visit__c,  Interview_End_Date__c,  Cluster__c, Cluster__r.Name,  Cluster__r.Pincode__c, Cluster__r.City__c , Cluster__r.State__c , Cluster__r.Town_Village__c , Operator__c,  Operator__r.CAFID__c, Operator__r.Name, Local_Operator__c , Local_Operator__r.LCO_Partner_Code__c,Local_Operator__r.Name,Sampling__c, (SELECT  Id,  Name,  Survey_Date__c,  Technician_Number__c,  Head_end__c,   Sub_District_Name__c,  Pincode__c,  Smart_Card_ID__c,  STB_ID_GOS_STB_ID__c,  Case__c,  State__c,  City__c,District__c,VC_No__c,  Town_Village__c FROM Survey__r) FROM Case where Sampling__r.Name=: samplingNo';
        return Database.getQueryLocator(query);  
    }
    
    global void execute(Database.BatchableContext BC, List<Case> caList){
        
        List<caseLister> NCaseList = new List<caseLister>();
        for(Case c:caList){
            for(Survey__c sv:c.Survey__r){
               caseLister cn = new caseLister();
               cn.clusterNo = c.Cluster__r.Name;
               cn.lcoId = c.Local_Operator__r.LCO_Partner_Code__c;
               cn.lcoName = c.Local_Operator__r.Name;
               cn.pincode = c.Cluster__r.Pincode__c;
               cn.state = c.Cluster__r.State__c;
               cn.district = c.Cluster__r.District__c;
               cn.city = c.Cluster__r.City__c;
               cn.oprId = c.Operator__r.CAFID__c;
               cn.oprName = c.Operator__r.Name;
               cn.stbNo = sv.STB_ID_GOS_STB_ID__c;
               cn.vcNo = sv.VC_No__c;
               cn.smartCardId = sv.Smart_Card_ID__c;
               cn.sfSurveyId = sv.Id;
               NCaseList.add(cn);
               
                
            }
            
        }
        
       //System.debug('NCaseList========>'+NCaseList);
       
       String clusJSON =JSON.serialize(NCaseList);
       
         
        Http h = new Http();
        HttpRequest req = new HttpRequest();

        req.setMethod('POST');
        req.setTimeout(120000);
        req.setHeader('Content-type', 'application/json');
        // req.setEndpoint('http://66.70.152.185:4300/api/insertClusters'); //sandbox url
         String url = Label.Integration_URL + '/insertClusters';
        req.setEndpoint(url); //sandbox url
        
        
        req.setBody(clusJSON);
        
        try{
            HttpResponse res = h.send(req);
            System.debug('res=======>' +res.getBody());
            
        }catch(System.calloutException e){
            System.debug('Exception=======>' +e);
        }
        
        
    }
    
    global void finish(Database.BatchableContext BC) {
         
    }
    
    public class caseLister{
       public String sfSurveyId;
       public String clusterNo;
       public String lcoId;
       public String lcoName;
       public String pincode;
       public String state;
       public String district;
       public String city;
       public String oprId;
       public String oprName;
       public String stbNo;
       public String vcNo;
       public String smartCardId;

    }
}