BARC UAT/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Code__c</fullName>
        <label>LCO Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technician_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician No</label>
        <referenceTo>Operator_Technician__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Cluster Items</relationshipLabel>
        <relationshipName>Cluster_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STB_ID__c</fullName>
        <label>STB ID/ GOS STB ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card_ID__c</fullName>
        <label>Smart Card ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_No__c</fullName>
        <label>VC No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Sr No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Local_Operator__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipName>Local_Operators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner / Local Operator</label>
    <nameField>
        <label>LCO / Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner / Local Operators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Operator__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Operator</label>
    <nameField>
        <label>Operator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Sampling__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Code__c</fullName>
        <label>LCO Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_No__c</fullName>
        <label>VC No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sampling</label>
    <nameField>
        <label>Sampling No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Samplings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <formula>Case__r.Cluster__r.District__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.Pincode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pincode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_ID_GOS_STB_ID__c</fullName>
        <label>STB ID/ GOS STB ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card_ID__c</fullName>
        <label>Smart Card ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Case__r.Cluster__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <formula>Case__r.Cluster__r.Sampling__r.Town_Village__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Town Village</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_No__c</fullName>
        <label>VC No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/GenerateClusterCaseBatch.cls
global class GenerateClusterCaseBatch implements Database.Batchable < sObject > {
    global String samplingNo {
        get;
        set;
    }
    global GenerateClusterCaseBatch(String smNo) {
        samplingNo = smNo;
        System.debug('In Constructor I am getting sampling number-->'+samplingNo);
    }
    
    
    
    

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('samplingNo before query-->' + samplingNo);
        
       	String query = 'SELECT  Id, Name, Operator__c, District__c,Technician_No__c,  City__c,  State__c,  Pincode__c,  Town_Village__c,  LCO_Code__c, Local_Operator__c, Sampling__c,( SELECT  Id,  Name,  Cluster__c,  Smart_Card_ID__c,  STB_ID__c,  STB_Type__c,VC_No__c FROM Cluster_Items__r) FROM Cluster__c WHERE Sampling__r.Name =:samplingNo';
      
        
        System.debug('query-->'+query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List < Cluster__c > clusterList) {
        System.debug('clusterList in Execute method--->' + clusterList);

        Set < String > clusterId = new Set < String > ();
        Set < String > clusterItemId = new Set < String > ();

        for (Cluster__c c: clusterList) {
            for (Cluster_Item__c ci: c.Cluster_Items__r) {
                clusterId.add(c.id);
                System.debug('clusterId===' + clusterId);

                clusterItemId.add(ci.Id);
                System.debug('clusterItemId===' + clusterItemId);

            }
        }

        List < Case > caseList = new List < Case > ();

        for (Cluster__c c: clusterList) {

            Case ca = new Case();
            ca.Cluster__c = c.Id;
            ca.Operator__c = c.Operator__c;
            ca.Local_Operator__c = c.Local_Operator__c;
            ca.Sampling__c = c.Sampling__c;
            caseList.add(ca);
        }

        Insert caseList;



        List < Case > cas = [Select Id, Cluster__c, Operator__c FROM Case WHERE Cluster__c IN: clusterId];

        Map < String, String > CaseClusterMap = new Map < String, String > ();
        Set < String > CaseId = new Set < String > ();

        for (Case c: cas) {

            CaseClusterMap.put(c.Cluster__c, c.id);
            System.debug('CaseClusterMap====' + CaseClusterMap);

            CaseId.add(c.id);
            System.debug('CaseId===' + CaseId);
        }

        List < Survey__c > SurveyList = new List < Survey__c > ();
        for (Cluster__c c: clusterList) {
            for(Cluster_Item__c ci: c.Cluster_Items__r) {
            if (CaseClusterMap.get(c.Id) != null) {
                Survey__c s = new Survey__c();
                s.Case__c = CaseClusterMap.get(c.Id);
                s.Smart_Card_ID__c = ci.Smart_Card_ID__c;
                s.STB_ID_GOS_STB_ID__c= ci.Smart_Card_ID__c;
               // s.District__c = c.District__c;
                s.VC_No__c = ci.VC_No__c;
                SurveyList.add(s);

            }
          }
        }
        
        Insert SurveyList;
        System.debug('SurveyList===='+SurveyList);
        


    }

    global void finish(Database.BatchableContext BC) {

    }
}