BARC UAT/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

BARC UAT/src/objects/Local_Operator__c.object
<CustomObject>
    <fields>
        <fullName>CAFID__c</fullName>
        <label>CAFID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Partner_City__c</fullName>
        <label>LCO / Partner City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Partner_Code__c</fullName>
        <label>LCO / Partner Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCO_Partner_Country__c</fullName>
        <label>LCO / Partner Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipName>Local_Operators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner / Local Operator</label>
    <nameField>
        <label>LCO / Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner / Local Operators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Operator__c.object
<CustomObject>
    <fields>
        <fullName>CAFID__c</fullName>
        <label>CAFID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Operator</label>
    <nameField>
        <label>Operator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Operator_Technician__c.object
<CustomObject>
    <fields>
        <fullName>CAFID__c</fullName>
        <label>CAFID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipName>Operator_Technician</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipName>Operator_Technician</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technician_City__c</fullName>
        <label>Technician City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Operator User</label>
    <nameField>
        <label>Technician Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/CallCAFTechnicianAPITest.cls
@IsTest
private class CallCAFTechnicianAPITest {
    
    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            if (req.getEndpoint().endsWith('insertOperator')) {
                
                
                Boolean b = True;
                String reCode = '200';
                String fullJson = 'Here is my String JSON';
                String sta = 'OK';
                String Js = '{"data":[{"operator_id":21}],"flag":1,"Msg":"Operator Created Successfully"}';
                
                HttpResponse res = new HttpResponse();
                res.setBody(Js);
                res.setStatusCode(200);
                res.setStatus(sta);
                return res;
                
                
            } else  if (req.getEndpoint().endsWith('insertLCO')) {
                
                String sta = 'OK';
                String js = '{"data":[{"lco_id":65}],"flag":1,"Msg":"Operator Created Successfully"}';
                HTTPResponse res = new HTTPResponse();
                res.setBody(js);
                res.setHeader('Content-Type', 'application/json');
                res.setStatusCode(200);
                res.setStatus(sta);
                return res;
            }
             else  if (req.getEndpoint().endsWith('insertTech')) {
                
                String sta = 'OK';
                String js = '{"data":[{"lco_id":65}],"flag":1,"Msg":"Operator Created Successfully"}';
                HTTPResponse res = new HTTPResponse();
                res.setBody(js);
                res.setHeader('Content-Type', 'application/json');
                res.setStatusCode(200);
                res.setStatus(sta);
                return res;
            }
            
            return null;
        }
    }
    
    
    static testMethod void abc() {
        
        Operator__c op = new Operator__c();
        op.CAFID__c = 'test0123';
        op.City__c = 'Vashi';
        op.Country__c = 'India';
        op.Email__c = 'ravi@testgmail.com';
        
        insert op;
        
        Local_Operator__c lc = new Local_Operator__c();
        lc.Operator__c = op.Id;
        lc.LCO_Partner_City__c = 'Vashi';
        lc.LCO_Partner_Code__c = 'abctst';
        lc.LCO_Partner_Country__c = 'India';
        
        insert lc;
        
        Operator_Technician__c optc = new Operator_Technician__c();
        optc.CAFID__c = '123fdf';
        optc.Technician_City__c = 'vashi';
        
        insert optc;
        
        
        Test.startTest();
        System.debug('-----Second test Case----------');
        
        callCAFTechnicianAPI contro = new callCAFTechnicianAPI();
        callCAFTechnicianAPI.apiCallout(optc.Id);
        Test.setMock(HttpCalloutMock.class, new Mock());
        
        
        Test.stopTest();
        
    }
    
    @IsTest
    static void xyz() {
        Test.setMock(HttpCalloutMock.class, new Mock());
        
    }
}