BARC UAT/src/objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sampling__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sampling</label>
        <referenceTo>Sampling__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Cluster_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Cluster Items</relationshipLabel>
        <relationshipName>Cluster_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cluster Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Sr No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cluster Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Sampling__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STB_Type__c</fullName>
        <label>STB Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smart_Card__c</fullName>
        <label>Smart Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StbID__c</fullName>
        <label>STBID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town_Village__c</fullName>
        <label>Town Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sampling</label>
    <nameField>
        <label>Sampling No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Samplings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/GenerateClusterCaseBatchTest.cls
@isTest
public class GenerateClusterCaseBatchTest {

	public static testMethod void test() {
	    
	     Sampling__c scm = new Sampling__c(
	      Name = '101',                         // Sampling No
          Cluster__c = '55003978',                // Cluster
          STB_Type__c = 'GOSPELL',                // STB Type
          City__c = 'Ernakulam',                  // City
          StbID__c = '4D0038A30',                 // STBID
          State__c = 'RAJASTHAN',                 // State
          Status__c = 'Active',                   // Status
          Town_Village__c = '5 Psd B.O',          // Town Village
          Smart_Card__c = '127867565432',         // Smart Card
          Pincode__c = '110095'                  // Pincode
         );                     
	    insert scm;
	    
	    Cluster__c clus = new Cluster__c(
          Name = '55003973',                                // Cluster No
          Sampling__c = scm.id,                             // Sampling
          City__c = 'Aligarh',                              // City
          Pincode__c = '110012',                            // Pincode
          State__c = 'ANDHRA PRADESH',                      // State
          Town_Village__c = '(Gandhinagar) Sector 22 S.O'   // Town Village
        );
        insert clus;
        
        Cluster_Item__c cli = new Cluster_Item__c(cluster__c=clus.id);
        insert cli;
	     
	     Test.startTest();
	    
	    GenerateClusterCaseBatch gcc = new GenerateClusterCaseBatch('101');
	    
	    Database.executeBatch(gcc);
	    
	    Test.stopTest();

	}

}