BARC UAT/src/objects/Delivery_Challan__c.object
<CustomObject>
    <fields>
        <fullName>Declarations__c</fullName>
        <label>Declarations</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Delivery_Challan_Date__c</fullName>
        <label>Delivery Challan Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket_No__c</fullName>
        <label>Docket No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRN_Date__c</fullName>
        <label>GRN Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GRN_No__c</fullName>
        <label>GRN No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installer_Name__c</fullName>
        <label>Installer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Boxes__c</fullName>
        <label>Number of Boxes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packing List</label>
        <referenceTo>Packing_List__c</referenceTo>
        <relationshipLabel>Delivery Challan</relationshipLabel>
        <relationshipName>Delivery_Challan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Place_of_Supply__c</fullName>
        <label>Place of Supply</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Weight_Kg__c</fullName>
        <label>Shipment Weight (Kg.)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <summarizedField>Delivery_Challan_Line_Item__c.Copy_Total_Value__c</summarizedField>
        <summaryForeignKey>Delivery_Challan_Line_Item__c.Delivery_Challan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delivery Challan</label>
    <nameField>
        <displayFormat>DC-{0}</displayFormat>
        <label>Delivery Challan No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Challan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Delivery_Challan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CGST_Amount__c</fullName>
        <formula>Kitting_Amount__c * ( CGST__c / 100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CGST Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CGST__c</fullName>
        <formula>IF(Is_IGST__c == false, GST_Rate__c/2, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CGST %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Copy_Total_Value__c</fullName>
        <label>Copy Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delivery_Challan__c</fullName>
        <label>Delivery Challan</label>
        <referenceTo>Delivery_Challan__c</referenceTo>
        <relationshipLabel>Delivery Challan Line Items</relationshipLabel>
        <relationshipName>Delivery_Challan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GST_Rate__c</fullName>
        <label>GST Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IGST_Amount__c</fullName>
        <formula>Kitting_Amount__c * ( IGST__c / 100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IGST Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IGST__c</fullName>
        <formula>IF(Is_IGST__c == true,GST_Rate__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IGST %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_IGST__c</fullName>
        <formula>IF( Delivery_Challan__r.Packing_List__r.Bill_To_State__c == &apos;Maharashtra&apos;, false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is IGST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kitting_Amount__c</fullName>
        <label>Kitting Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Kitting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Delivery Challan Line Items</relationshipLabel>
        <relationshipName>Delivery_Challan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SGST_Amount__c</fullName>
        <formula>Kitting_Amount__c * (  SGST__c / 100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SGST Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SGST__c</fullName>
        <formula>IF(Is_IGST__c == false, GST_Rate__c/2, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SGST %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Kitting_Amount__c +  CGST_Amount__c +  IGST_Amount__c +  SGST_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Delivery Challan Line Item</label>
    <nameField>
        <displayFormat>DCL-{0}</displayFormat>
        <label>Delivery Challan Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Challan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting__c.object
<CustomObject>
    <label>Kitting</label>
    <nameField>
        <displayFormat>AC#{00000000}</displayFormat>
        <label>Kitting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name:</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PLN-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Packing List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/DeliveryChallanPDFCls.cls
public class DeliveryChallanPDFCls {
    
public Id deId{get;set;}
public Delivery_Challan__c dch{get;set;}
public List<Delivery_Challan_Line_Item__c> dchline {get;set;}

    public DeliveryChallanPDFCls(){
        
        deId=ApexPages.currentPage().getParameters().get('id');
        
        dch=[ SELECT  Id,  Name,  Delivery_Challan_Date__c,  Delivery_Mode__c,  Transporter_Name__c,  Place_of_Supply__c,  Number_of_Boxes__c,  Shipment_Weight_Kg__c,  Installer_Name__c,  
             Declarations__c,  Packing_List__c,  Docket_No__c,  Total_Amount__c,  GRN_No__c, GRN_Date__c FROM Delivery_Challan__c where id=:deId]; 
             
        dchline=[SELECT  Id,  Name,  Delivery_Challan__c,  Kitting__c,  Kitting_Amount__c,  Is_IGST__c,  Kitting__r.Name, 
                CGST__c,  SGST__c,  IGST__c,  CGST_Amount__c,  SGST_Amount__c,  IGST_Amount__c,  Total_Amount__c,  GST_Rate__c,  Copy_Total_Value__c FROM Delivery_Challan_Line_Item__c where
                Delivery_Challan__c=:deId];
    }

}