BARC UAT/src/objects/Delivery_Challan__c.object
<CustomObject>
    <label>Delivery Challan</label>
    <nameField>
        <displayFormat>DC-{0}</displayFormat>
        <label>Delivery Challan No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Challan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Delivery_Challan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Challan__c</fullName>
        <label>Delivery Challan</label>
        <referenceTo>Delivery_Challan__c</referenceTo>
        <relationshipLabel>Delivery Challan Line Items</relationshipLabel>
        <relationshipName>Delivery_Challan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery Challan Line Item</label>
    <nameField>
        <displayFormat>DCL-{0}</displayFormat>
        <label>Delivery Challan Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Challan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/classes/DeliveryChallanPDFClsTest.cls
@isTest
public class DeliveryChallanPDFClsTest {

	public static testMethod void test() {
	    
	    Delivery_Challan__c dch = new Delivery_Challan__c();
	    insert dch;
	    
	    Delivery_Challan_Line_Item__c dcl = new Delivery_Challan_Line_Item__c(Delivery_Challan__c=dch.id);
	    insert dcl;
	    
	    
	    ApexPages.currentPage().getParameters().put('id', dch.id);
	    
	    DeliveryChallanPDFCls dcp = new DeliveryChallanPDFCls();

	}

}