BARC UAT/src/objects/Delivery_Challan__c.object
<CustomObject>
    <fields>
        <fullName>Declarations__c</fullName>
        <label>Declarations</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Delivery_Challan_Date__c</fullName>
        <label>Delivery Challan Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket_No__c</fullName>
        <label>Docket No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRN_Date__c</fullName>
        <label>GRN Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GRN_No__c</fullName>
        <label>GRN No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installer_Name__c</fullName>
        <label>Installer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Boxes__c</fullName>
        <label>Number of Boxes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packing List</label>
        <referenceTo>Packing_List__c</referenceTo>
        <relationshipLabel>Delivery Challan</relationshipLabel>
        <relationshipName>Delivery_Challan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Place_of_Supply__c</fullName>
        <label>Place of Supply</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Weight_Kg__c</fullName>
        <label>Shipment Weight (Kg.)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <summarizedField>Delivery_Challan_Line_Item__c.Copy_Total_Value__c</summarizedField>
        <summaryForeignKey>Delivery_Challan_Line_Item__c.Delivery_Challan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delivery Challan</label>
    <nameField>
        <displayFormat>DC-{0}</displayFormat>
        <label>Delivery Challan No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Challan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Delivery_Challan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Challan__c</fullName>
        <label>Delivery Challan</label>
        <referenceTo>Delivery_Challan__c</referenceTo>
        <relationshipLabel>Delivery Challan Line Items</relationshipLabel>
        <relationshipName>Delivery_Challan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Kitting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Delivery Challan Line Items</relationshipLabel>
        <relationshipName>Delivery_Challan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Kitting_Amount__c +  CGST_Amount__c +  IGST_Amount__c +  SGST_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Delivery Challan Line Item</label>
    <nameField>
        <displayFormat>DCL-{0}</displayFormat>
        <label>Delivery Challan Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Challan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting__c.object
<CustomObject>
    <label>Kitting</label>
    <nameField>
        <displayFormat>AC#{00000000}</displayFormat>
        <label>Kitting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Local_Operator__c.object
<CustomObject>
    <label>Partner / Local Operator</label>
    <nameField>
        <label>LCO / Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner / Local Operators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Operator__c.object
<CustomObject>
    <label>Operator</label>
    <nameField>
        <label>Operator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Email__c</fullName>
        <label>Bill To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Bill_To_Name__c</fullName>
        <label>Bill To Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Packing Lists</relationshipLabel>
        <relationshipName>Packing_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To_Phone__c</fullName>
        <label>Bill To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Bill_To_Pincode__c</fullName>
        <label>Bill To Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <label>Bill To State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <label>Ship To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Ship To Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Email__c</fullName>
        <label>Ship To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_To_Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Packing Lists</relationshipLabel>
        <relationshipName>Packing_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Name__c</fullName>
        <label>Ship To Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Packing Lists (Ship To Operator)</relationshipLabel>
        <relationshipName>Packing_Lists1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Phone__c</fullName>
        <label>Ship To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_To_Pincode__c</fullName>
        <label>Ship To Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <label>Ship To State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name:</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PLN-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Packing List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/AIMS.cls
@RestResource(urlMapping = '/sfdc_aims/*')
global class AIMS {

    @HttpGet
    global static void getDCDetails() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        String dc_No = req.params.get('dc_No');

        System.debug('dc_No ======' + dc_No);
        try {
            List < Delivery_Challan__c > dlData = [SELECT Id, Name, Total_Amount__c, Docket_No__c, (SELECT Id, Kitting__r.Name FROM Delivery_Challan_Line_Items__r), Delivery_Challan_Date__c, Delivery_Mode__c, Transporter_Name__c, Place_of_Supply__c, Number_of_Boxes__c, Shipment_Weight_Kg__c, Installer_Name__c, Declarations__c,
                Packing_List__r.Ship_To_Local_Operator__r.CAFID__c, Packing_List__r.Ship_To_Operator__r.CAFID__c, Packing_List__r.Bill_To_Operator__r.CAFID__c, Packing_List__r.Bill_To_Name__c, Packing_List__r.Bill_To_Phone__c, Packing_List__r.Bill_To_Email__c, Packing_List__r.Bill_To_State__c, Packing_List__r.Bill_To_City__c, Packing_List__r.Bill_To_Pincode__c,
                Packing_List__r.Ship_To_Name__c, Packing_List__r.Ship_To_Phone__c, Packing_List__r.Ship_To_Email__c, Packing_List__r.Ship_To_State__c, Packing_List__r.Ship_To_Country__c, Packing_List__r.Ship_To_City__c, Packing_List__r.Ship_To_Pincode__c FROM Delivery_Challan__c WHERE Name =: dc_No
            ];

            if (dlData.size() != 0) {
                res.responseBody = Blob.valueOf(JSON.serialize(dlData[0]));
                res.statusCode = 200;
            } else {
                res.responseBody = Blob.valueOf('No Delivery Challan found by this DC No');
                res.statusCode = 200;
            }
        } catch (Exception e) {

            res.responseBody = Blob.valueOf(e.getMessage());
            res.statusCode = 500;

        }
    }

    @HttpPost
    global static resp savegrnDetails() {

        RestResponse res;
        try {
            resp rsp = new resp();
            String jsonString = RestContext.request.requestBody.toString();
            System.debug('jsonString' + jsonString);

            DelvJSON devData = new DelvJSON();
            devData = parse(jsonString);


            Delivery_Challan__c dch = new Delivery_Challan__c();
            dch.id = devData.deId;
            dch.GRN_No__c = devData.grnum;
            dch.GRN_Date__c = Date.valueOf(devData.grndate);

            update dch;
            
            
            rsp.status = true;
            rsp.msg = 'Successfully Updated Survey Data.';
            rsp.statusCode = '200';
            return rsp;

        } catch (Exception e) {
            resp rsp = new resp();
            rsp.status = false;
            rsp.msg = String.valueOf(e.getMessage());
            rsp.statusCode = '400';
            System.debug(e);
            return rsp;
        }


    }

    global class DelvJSON {

        public String deId;
        public String grnum;
        public String grndate;
    }

    global class resp {
        Boolean status;
        String msg;
        String statusCode;

    }

    global static DelvJSON parse(String json) {
        return (DelvJSON) System.JSON.deserialize(json, DelvJSON.class);
    }
    
}