BARC UAT/src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0}</displayFormat>
        <label>Inventory  No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Inventory_Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Inventory Products</relationshipLabel>
        <relationshipName>Inventory_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Added_To_Kitting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Added To Kitting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <label>Remark</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ok</fullName>
                </value>
                <value>
                    <fullName>Not Ok</fullName>
                </value>
                <value>
                    <fullName>Retest</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Faulty</fullName>
                </value>
                <value>
                    <fullName>Write-Off</fullName>
                </value>
                <value>
                    <fullName>In Transit (Active)</fullName>
                </value>
                <value>
                    <fullName>Faulty In Transit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Inventory Products</relationshipLabel>
        <relationshipName>Inventory_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>Warehouse__c</referenceTo>
        <relationshipLabel>Inventory Products</relationshipLabel>
        <relationshipName>Inventory_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Product</label>
    <nameField>
        <label>Inventory Product Sr No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting__c.object
<CustomObject>
    <fields>
        <fullName>Is_Added_To_Kitting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Added To Kitting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kitting_Type__c</fullName>
        <label>Kitting Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Kitting_Type_Master</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installed</fullName>
                </value>
                <value>
                    <fullName>Faulty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Kitting</label>
    <nameField>
        <displayFormat>AC#{00000000}</displayFormat>
        <label>Kitting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting_Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Product</label>
        <referenceTo>Inventory_Product__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kitting__c</fullName>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Kitting Product</label>
    <nameField>
        <displayFormat>KP-{0}</displayFormat>
        <label>Kitting Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Warehouse__c.object
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/Testing_Kitting.cls
global class Testing_Kitting {
    public Id invId {
        get;
        set;
    }
    public Inventory__c invt {
        get;
        set;
    }
    public String invLList {
        get;
        set;
    }
    public String productList {
        get;
        set;
    }
    
    public String kittingTypeList{get;set;}
    
    public Testing_Kitting() {
        invId = ApexPages.currentPage().getParameters().get('id');
        invt = [select id, Name, Product__c, Product__r.Name from Inventory__c where id =: invId];

        List < Inventory_Product__c > invLData = new List < Inventory_Product__c > ();
        invLData = [SELECT Id, Name, Supplier__c, Status__c, Warehouse__c, Inventory__c, Inventory__r.Name, Remark__c FROM Inventory_Product__c where Inventory__c =: invId and Is_Added_To_Kitting__c = false and(Status__c =: ''
            or Status__c =: Null)];
        invLList = JSON.serialize(invLData);

        List < Inventory__c > productData = [select id, Name, Product__c, Product__r.Name from Inventory__c where Product__c !=: invt.Product__c];
        productList = JSON.serialize(productData);
        
        Schema.DescribeFieldResult F = Kitting__c.Kitting_Type__c.getDescribe();
        Schema.sObjectField T = F.getSObjectField();
        List<PicklistEntry> entries = T.getDescribe().getPicklistValues();
        kittingTypeList = JSON.serialize(entries);
    }
    
    @RemoteAction
    global static List<Inventory_Product__c> getInvProducts(String pId) {
        List<Inventory_Product__c> invpList  = [SELECT Id, Name, Supplier__c, Status__c, Warehouse__c, Inventory__c, Inventory__r.Name, Remark__c FROM Inventory_Product__c where Inventory__r.Product__c =: pId and Is_Added_To_Kitting__c = false and(Status__c =: ''
            or Status__c =: Null)];
        return invpList;
    }
    
    
    @RemoteAction
    global static Boolean saveInvProductsAsFaulty(String invJSON) {
        System.debug('invJSON ====='+invJSON);
        Inventory_Product__c invp = new Inventory_Product__c();
        invp = parseInvJSON(invJSON);
        System.debug('invp ====='+invp);
        try{
            update invp;
            return true;
        }catch (System.CalloutException e) {
           System.debug(e.getMessage());
            //System.debug(response.toString());
            return false;
        }
    }
    
    global static Inventory_Product__c parseInvJSON(String json) {
        return (Inventory_Product__c) System.JSON.deserialize(json, Inventory_Product__c.class);
    }
    
    @RemoteAction
    global static String createKitting(String invJSON,String kittingType) {
        List<Inventory_Product__c> invpList = new List<Inventory_Product__c>();
        
        
        try{
            Kitting__c k = new Kitting__c();
            k.Kitting_Type__c = kittingType;
            insert k;

            List < Kitting_Product__c > kittingProList = new List < Kitting_Product__c > ();
            invpList = parseInvListJSON(invJSON);
            
            for (Inventory_Product__c i: invpList) {
                Kitting_Product__c kp = new Kitting_Product__c();
                kp.Inventory_Product__c = i.Id;
                kp.Kitting__c = k.Id;

                kittingProList.add(kp);

                i.Is_Added_To_Kitting__c = true;
                i.Status__c = 'Ok';
            }

            insert kittingProList;
            
            update invpList;
            
            Kitting__c kittingData= [SELECT Id,Name FROM Kitting__c WHERE Id=: k.Id];
            
            String srNo = kittingData.Name;
            return srNo;
            
        }catch (Exception e) {
            System.debug(e.getMessage());
            
            String ex = 'Error';
            //System.debug(response.toString());
            return ex;
        }
    }
    
    
    global static List<Inventory_Product__c> parseInvListJSON(String json) {
        return (List<Inventory_Product__c>) System.JSON.deserialize(json, List<Inventory_Product__c>.class);
    }
    
    
    

}