BARC UAT/src/objects/Inventory_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <formula>Inventory__r.Product__r.Product_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Inventory Products</relationshipLabel>
        <relationshipName>Inventory_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Product</label>
    <nameField>
        <label>Inventory Product Sr No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <label>Bill To Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Email__c</fullName>
        <label>Bill To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Bill_To_Name__c</fullName>
        <label>Bill To Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Phone__c</fullName>
        <label>Bill To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Bill_To_Pincode__c</fullName>
        <label>Bill To Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <label>Bill To State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Declaration__c</fullName>
        <label>Declaration</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Date_Time__c</fullName>
        <label>Invoice Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Packing_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packing List</label>
        <referenceTo>Packing_List__c</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <label>Ship To Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <label>Ship To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Ship To Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Email__c</fullName>
        <label>Ship To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_To_Name__c</fullName>
        <label>Ship To Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Phone__c</fullName>
        <label>Ship To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_To_Pincode__c</fullName>
        <label>Ship To Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <label>Ship To State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>TI-TN-{0}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Kitting_Amount__c</fullName>
        <label>Kitting Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Kitting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Invoice Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting__c.object
<CustomObject>
    <label>Kitting</label>
    <nameField>
        <displayFormat>AC#{00000000}</displayFormat>
        <label>Kitting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting_Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Product</label>
        <referenceTo>Inventory_Product__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kitting__c</fullName>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Kitting Product</label>
    <nameField>
        <displayFormat>KP-{0}</displayFormat>
        <label>Kitting Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <label>Bill To Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Email__c</fullName>
        <label>Bill To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Bill_To_Name__c</fullName>
        <label>Bill To Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Packing Lists</relationshipLabel>
        <relationshipName>Packing_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To_Phone__c</fullName>
        <label>Bill To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Bill_To_Pincode__c</fullName>
        <label>Bill To Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <label>Bill To State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Declaration__c</fullName>
        <label>Declaration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <label>Ship To Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <label>Ship To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Ship To Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Email__c</fullName>
        <label>Ship To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_To_Local_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Local Operator</label>
        <referenceTo>Local_Operator__c</referenceTo>
        <relationshipLabel>Packing Lists</relationshipLabel>
        <relationshipName>Packing_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Name__c</fullName>
        <label>Ship To Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Operator</label>
        <referenceTo>Operator__c</referenceTo>
        <relationshipLabel>Packing Lists (Ship To Operator)</relationshipLabel>
        <relationshipName>Packing_Lists1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Phone__c</fullName>
        <label>Ship To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_To_Pincode__c</fullName>
        <label>Ship To Pincode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <label>Ship To State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name:</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PLN-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Packing List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Kitting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Packing List Line Items</relationshipLabel>
        <relationshipName>Packing_List_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packing_List__c</fullName>
        <label>Packing List</label>
        <referenceTo>Packing_List__c</referenceTo>
        <relationshipLabel>Packing List Line Items</relationshipLabel>
        <relationshipName>Packing_List_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Packing List Line Items</relationshipLabel>
        <relationshipName>Packing_List_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Packing List Line Item</label>
    <nameField>
        <displayFormat>PLLI-{0000000}</displayFormat>
        <label>Packing List Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing List Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/GenarateInvoice.cls
public class GenarateInvoice {
    public String packingListId{get;set;}
    public GenarateInvoice(){
        System.debug('load this');
        packingListId = ApexPages.currentPage().getParameters().get('id');
    }
    
    public PageReference generate(){
        System.debug('call this method on load ======='+packingListId);
        Packing_List__c pdata = [ SELECT  Id,  Name, ( SELECT  Id,  Name,  Packing_List__c,  Kitting__c FROM Packing_List_Line_Items__r), Bill_To_Name__c,  Bill_To_Address__c,  Bill_To_Phone__c,  Ship_To_Name__c,  Ship_To_Address__c,  Ship_To_Phone__c,  Ship_To_Email__c,  Bill_To_Operator__c,  Ship_To_Operator__c,  Ship_To_Local_Operator__c,  Bill_To_Email__c,  Bill_To_State__c,  Ship_To_State__c,  Bill_To_Country__c,  Ship_To_Country__c,  Bill_To_City__c,  Ship_To_City__c,  Bill_To_Pincode__c,  Ship_To_Pincode__c,  Transporter_Name__c,  Delivery_Mode__c,  Purpose__c,  Declaration__c FROM Packing_List__c WHERE Id=:packingListId];
        Set<Id> kittingIds = new Set<Id>();
        for(Packing_List_Line_Item__c pl: pdata.Packing_List_Line_Items__r){
            kittingIds.add(pl.Kitting__c);
        }
        List<Kitting__c> kittingData = [ SELECT  Id,  Name,( SELECT  Id,  Name,  Kitting__c,  Product__c,  Supplier__c,  Inventory_Product__c,Inventory_Product__r.Product_Cost__c FROM Kitting_Products__r) FROM Kitting__c WHERE Id in: kittingIds];
        Map<String,List<Kitting_Product__c>> kittingPMap = new Map<String,List<Kitting_Product__c>>();
        
        for(Kitting__c k: kittingData){
            kittingPMap.put(k.Id,k.Kitting_Products__r);
        }
        
        
        List<Invoice__c> inlist = [SELECT Id FROM Invoice__c WHERE Packing_List__c=: packingListId];
        
        if(inlist.size() == 0){
            Invoice__c d = new Invoice__c();
            d.Packing_List__c = pdata.Id;
            d.Invoice_Date_Time__c = DateTime.now();
            d.Transporter_Name__c = pdata.Transporter_Name__c;
            d.Delivery_Mode__c = pdata.Delivery_Mode__c;
            d.Declaration__c = pdata.Declaration__c;
            
            insert d;
            
            
            List<Invoice_Line_Item__c> NDlineItems = new List<Invoice_Line_Item__c>();
            for(Packing_List_Line_Item__c pl: pdata.Packing_List_Line_Items__r){
                Invoice_Line_Item__c dl = new Invoice_Line_Item__c();
                dl.Invoice__c = d.Id;
                dl.Kitting__c = pl.Kitting__c;
                
                Double amount = 0;
                if(kittingPMap.get(pl.Kitting__c) != null){
                    List<Kitting_Product__c> kittingpList = kittingPMap.get(pl.Kitting__c) ;
                    for(Kitting_Product__c kl: kittingpList){
                        amount = amount + kl.Inventory_Product__r.Product_Cost__c;
                    }
                    dl.Kitting_Amount__c = amount;
                }
                
                NDlineItems.add(dl);
                
            }
            
            insert NDlineItems;
        } 
        
        
        PageReference pageRef = new PageReference('/' + packingListId);
        pageRef.setRedirect(true);
        return pageRef;
    }
}