BARC UAT/src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0}</displayFormat>
        <label>Inventory  No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Inventory_Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Inventory Products</relationshipLabel>
        <relationshipName>Inventory_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Added_To_Kitting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Added To Kitting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <formula>Inventory__r.Product__r.Product_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <label>Remark</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ok</fullName>
                </value>
                <value>
                    <fullName>Not Ok</fullName>
                </value>
                <value>
                    <fullName>Retest</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Faulty</fullName>
                </value>
                <value>
                    <fullName>Write-Off</fullName>
                </value>
                <value>
                    <fullName>In Transit (Active)</fullName>
                </value>
                <value>
                    <fullName>Faulty In Transit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory Product</label>
    <nameField>
        <label>Inventory Product Sr No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/Testing_KittingTest.cls
@isTest
public class Testing_KittingTest {

	public static testMethod void test() {
	    
	    Product2 prod = new Product2(
          Name = 'GSM SIM',              // Product Name
          QuantityUnitOfMeasure = 'Each',  // Product UOM
          Product_Cost__c = 90.00,         // Product Cost
          IsActive = true                 // Active
        );
        insert prod;
	    
	    Id rt=[select id from RecordType where sObjectType='Inventory__c' and Name='Unit Inventory'].id;
	    
	    Inventory__c inv = new Inventory__c(
          RecordTypeId = rt,    // Record Type
          Product__c = prod.id  // Product
        );
        insert inv;
	    
	    List<Inventory_Product__c> invpList = new List<Inventory_Product__c>();
	    Inventory_Product__c invp = new Inventory_Product__c(
          Name = 'testpord',   // Inventory Product Sr No.
          Inventory__c = inv.id,  // Inventory
          Is_Added_To_Kitting__c = false,    // Is Added To Kitting
          Status__c = 'Ok',              // Status
          Remark__c = 'test'                // Remark
        );
        insert invp;
        invpList.add(invp);
        
        Inventory_Product__c invp1 = new Inventory_Product__c(
          Name = 'testpord1',   // Inventory Product Sr No.
          Inventory__c = inv.id,  // Inventory
          Is_Added_To_Kitting__c = false,    // Is Added To Kitting
          Status__c = 'Ok',              // Status
          Remark__c = 'test'                // Remark
        );
        insert invp1;
        invpList.add(invp1);
        
        
	    
	    ApexPages.currentPage().getParameters().put('id', inv.id);
	    Testing_Kitting tek = new Testing_Kitting();
	    Testing_Kitting.getInvProducts(prod.id);
	    String js=JSON.serialize(invpList);
	    //Testing_Kitting.parseInvJSON(js);
	    Testing_Kitting.createKitting(js,'Airtel Kitting');
	    

	}
	
	public static testMethod void test1() {
	    
	    Product2 prod = new Product2(
          Name = 'GSM SIM',              // Product Name
          QuantityUnitOfMeasure = 'Each',  // Product UOM
          Product_Cost__c = 90.00,         // Product Cost
          IsActive = true                 // Active
        );
        insert prod;
	    
	    Id rt=[select id from RecordType where sObjectType='Inventory__c' and Name='Unit Inventory'].id;
	    
	    Inventory__c inv = new Inventory__c(
          RecordTypeId = rt,    // Record Type
          Product__c = prod.id  // Product
        );
        insert inv;
	    
	    Inventory_Product__c invp = new Inventory_Product__c(
          Name = 'testpord',   // Inventory Product Sr No.
          Inventory__c = inv.id,  // Inventory
          Is_Added_To_Kitting__c = false,    // Is Added To Kitting
          Status__c = 'Faulty',              // Status
          Remark__c = 'test'                // Remark
        );
        insert invp;
	    
	    ApexPages.currentPage().getParameters().put('id', inv.id);
	    Testing_Kitting tek = new Testing_Kitting();
	    Testing_Kitting.getInvProducts(prod.id);
	    String js=JSON.serialize(invp);
	    //Testing_Kitting.parseInvJSON(js);
	    Testing_Kitting.saveInvProductsAsFaulty(js);
	    

	}

}