BARC UAT/src/objects/Inventory_Product__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ok</fullName>
                </value>
                <value>
                    <fullName>Not Ok</fullName>
                </value>
                <value>
                    <fullName>Retest</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Faulty</fullName>
                </value>
                <value>
                    <fullName>Write-Off</fullName>
                </value>
                <value>
                    <fullName>In Transit (Active)</fullName>
                </value>
                <value>
                    <fullName>Faulty In Transit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventory Product</label>
    <nameField>
        <label>Inventory Product Sr No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installed</fullName>
                </value>
                <value>
                    <fullName>Faulty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Kitting</label>
    <nameField>
        <displayFormat>AC#{00000000}</displayFormat>
        <label>Kitting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting_Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Product</label>
        <referenceTo>Inventory_Product__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kitting__c</fullName>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Kitting Products</relationshipLabel>
        <relationshipName>Kitting_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Kitting Product</label>
    <nameField>
        <displayFormat>KP-{0}</displayFormat>
        <label>Kitting Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Return_Receipt__c.object
<CustomObject>
    <fields>
        <fullName>Build_To_Address__c</fullName>
        <label>Build To Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Build_To_Email__c</fullName>
        <label>Build To Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Build_To_Name__c</fullName>
        <label>Build To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Build_To_Phone__c</fullName>
        <label>Build To Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Challan_Date__c</fullName>
        <label>Challan Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Challan_No__c</fullName>
        <label>Challan No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRN_Date__c</fullName>
        <label>GRN Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRN_No__c</fullName>
        <label>GRN No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L_R_No__c</fullName>
        <label>L R No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Return_No__c</fullName>
        <label>Purchase Return No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <label>Ship To Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Email__c</fullName>
        <label>Ship To Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Name__c</fullName>
        <label>Ship To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Phone__c</fullName>
        <label>Ship To Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_Site__c</fullName>
        <label>Warehouse Site</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Return Receipt</label>
    <nameField>
        <displayFormat>RR-{0}</displayFormat>
        <label>Return Receipt No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Return_Receipt_Details__c.object
<CustomObject>
    <fields>
        <fullName>GRN_No__c</fullName>
        <label>GRN No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_UOM__c</fullName>
        <label>Item UOM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Return_No__c</fullName>
        <label>Purchase Return No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Receipt__c</fullName>
        <label>Return Receipt</label>
        <referenceTo>Return_Receipt__c</referenceTo>
        <relationshipLabel>Return Receipt Details</relationshipLabel>
        <relationshipName>Return_Receipt_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sr_No__c</fullName>
        <label>Sr No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Return Receipt Details</label>
    <nameField>
        <displayFormat>RRD-{0}</displayFormat>
        <label>Return Receipt Details No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Receipt Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/classes/SaveReturnReciept.cls
@RestResource(urlMapping = '/sfdc_rre/*')
global class SaveReturnReciept {

    @HttpPost
    global static resp saveReturnReceiptData() {

        RestResponse res;
        try {
            resp rsp = new resp();
            String jsonString = RestContext.request.requestBody.toString();
            System.debug('jsonString' + jsonString);

            List<recJSON> reclist = new List<recJSON>();
            reclist=parse(jsonString);
            
            Set<String> kName = new Set<String>();   
            Set<String> InvPSet = new Set<String>();   
            List<Kitting__c> kiList = new List<Kitting__c>();
            
            List<Return_Receipt_Details__c> rdList = new List<Return_Receipt_Details__c>();
            
            for(recJSON rj:recList){
                
                Return_Receipt__c ret = new Return_Receipt__c();
                ret.Purchase_Return_No__c=rj.PURCHASE_RETURN_NO;
                ret.GRN_No__c=rj.GRN_NUMBER;
                ret.GRN_Date__c=rj.GRN_DATE;
                ret.Challan_No__c=rj.CHALLAN_NUMBER;
                ret.Challan_Date__c=rj.CHALLAN_DATE;
                ret.Warehouse_Site__c=rj.WAREHOUSE_SITE;
                ret.L_R_No__c=rj.LR_NUMBER;
                ret.Reason__c=rj.REASONE;
                ret.Build_To_Name__c=rj.BUOLD_TO_NAME;
                ret.Build_To_Email__c=rj.BUOLD_TO_EMAIL;
                ret.Build_To_Phone__c=rj.BUOLD_TO_PHONE;
                ret.Build_To_Address__c=rj.BUOLD_TO_ADDRS;
                ret.Ship_To_Name__c=rj.SHIP_TO_NAME;
                ret.Ship_To_Email__c=rj.SHIP_TO_EMAIL;
                ret.Ship_To_Phone__c=rj.SHIP_TO_PHONE;
                ret.Ship_To_Address__c=rj.SHIP_TO_ADDRS;
                
                insert ret;
                
                System.debug(ret);
                kName = new Set<String>();   
                for(Details de:rj.details){
                    Return_Receipt_Details__c rde = new Return_Receipt_Details__c();
                    rde.Return_Receipt__c=ret.id;
                    rde.Sr_No__c=de.S_NO;
                    rde.Purchase_Return_No__c=de.PURCHASE_RETURN_NO;
                    rde.GRN_No__c=de.GRN_NUMBER;
                    rde.Item_Code__c=de.ITEM_CODE;
                    rde.Item_UOM__c=de.ITEM_UOM;
                    rde.Remarks__c=de.REMARKS;
                    
                    kName.add(rde.Item_Code__c);
                    
                    rdList.add(rde);
                }
            }
            
            insert rdlist;
            
            kiList = new List<Kitting__c>();
            for(Kitting__c ki:[select Id,Name, (SELECT id,Name, Kitting__c, Kitting__r.Status__c, Kitting__r.Name, Inventory_Product__c from Kitting_Products__r) FROM Kitting__c WHERE Name in: kName ]){
                
                // Kitting__c ki = new Kitting__c();
                // ki.id=kp.Kitting__c;
                ki.Status__c='Faulty';
                kiList.add(ki);
                for(Kitting_Product__c kp: ki.Kitting_Products__r){
                    InvPSet.add(kp.Inventory_Product__c);
                }
            }
            
            update kiList;
            List<Inventory_Product__c> invpList = new List<Inventory_Product__c>();
            for(Inventory_Product__c ip:[select id from Inventory_Product__c where id IN:InvPSet]){
                
                Inventory_Product__c prod = new Inventory_Product__c();
                prod.id=ip.id;
                prod.Status__c='Faulty';
                invpList.add(prod);
            }
            
            update invpList;
            
            System.debug(rdlist);
            
            rsp.status = true;
            rsp.msg = 'Successfully Updated Return Reciept Data.';
            rsp.statusCode = '200';
            return rsp;

        } catch (Exception e) {
            resp rsp = new resp();
            rsp.status = false;
            rsp.msg = String.valueOf(e.getMessage());
            rsp.statusCode = '400';
            System.debug(e);
            return rsp;
        }


    }
    
    global class resp {
        Boolean status;
        String msg;
        String statusCode;

    }
    
    global class recJSON {

    	public String RR_ID;
    	public String PURCHASE_RETURN_NO;
    	public String GRN_NUMBER;
    	public String GRN_DATE;
    	public String CHALLAN_NUMBER;
    	public String CHALLAN_DATE;
    	public String WAREHOUSE_SITE;
    	public String LR_NUMBER;
    	public String REASONE;
    	public String BUOLD_TO_NAME;
    	public String BUOLD_TO_EMAIL;
    	public String BUOLD_TO_PHONE;
    	public String BUOLD_TO_ADDRS;
    	public String SHIP_TO_NAME;
    	public String SHIP_TO_EMAIL;
    	public String SHIP_TO_PHONE;
    	public String SHIP_TO_ADDRS;
    	public List<Details> details;
  
    }  
    
    public class Details {
		public String S_NO;
		public String PURCHASE_RETURN_NO;
		public String GRN_NUMBER;
		public String ITEM_CODE;
		public String ITEM_UOM;
		public String REMARKS;
	}
    	
	global static List<recJSON> parse(String json) {
		return (List<recJSON>) System.JSON.deserialize(json, List<recJSON>.class);
	}

}