BARC UAT/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Declaration__c</fullName>
        <label>Declaration</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket_Number__c</fullName>
        <label>Docket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Date_Time__c</fullName>
        <label>Invoice Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Boxes__c</fullName>
        <label>Number of Boxes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packing List</label>
        <referenceTo>Packing_List__c</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Weight__c</fullName>
        <label>Shipment (Weight )</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>TI-TN-{0}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CGST_Amount__c</fullName>
        <formula>Kitting_Amount__c * ( CGST__c / 100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CGST Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CGST__c</fullName>
        <formula>IF(Is_IGST__c == false, GST_Rate__c/2, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CGST %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GST_Rate__c</fullName>
        <label>GST Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IGST_Amount__c</fullName>
        <formula>Kitting_Amount__c * ( IGST__c / 100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IGST Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IGST__c</fullName>
        <formula>IF(Is_IGST__c == true,GST_Rate__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IGST %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_IGST__c</fullName>
        <formula>IF( Invoice__r.Packing_List__r.Bill_To_State__c == &apos;Maharashtra&apos;, false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is IGST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kitting_Amount__c</fullName>
        <label>Kitting Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Kitting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SGST_Amount__c</fullName>
        <formula>Kitting_Amount__c * (  SGST__c / 100 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SGST Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SGST__c</fullName>
        <formula>IF(Is_IGST__c == false, GST_Rate__c/2, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SGST %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Kitting_Amount__c +  CGST_Amount__c +  IGST_Amount__c +  SGST_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Invoice Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Kitting__c.object
<CustomObject>
    <label>Kitting</label>
    <nameField>
        <displayFormat>AC#{00000000}</displayFormat>
        <label>Kitting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List__c.object
<CustomObject>
    <fields>
        <fullName>Declaration__c</fullName>
        <label>Declaration</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delivery_Mode__c</fullName>
        <label>Delivery Mode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transporter_Name__c</fullName>
        <label>Transporter Name:</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PLN-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Packing List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/classes/TaxInvoicePDFCls.cls
public class TaxInvoicePDFCls {

public Id inId{get;set;}
public Invoice__c inv{get;set;}
public List<Invoice_Line_Item__c> invline {get;set;}
	
	public TaxInvoicePDFCls() {
	    
	    inId=ApexPages.currentPage().getParameters().get('id');
	    
	    inv=[SELECT  Id,  Name,  Invoice_Date_Time__c,  Transporter_Name__c,  Shipment_Weight__c,  Number_of_Boxes__c,  Docket_Number__c,  Packing_List__c,  
	        Delivery_Mode__c,  Declaration__c FROM Invoice__c where id=:inId];
	   
	    invline=[SELECT  Id,  Name,  Invoice__c,  CGST_Amount__c,  CGST__c,  GST_Rate__c,  IGST_Amount__c,  IGST__c,  Is_IGST__c,  Kitting_Amount__c,  Kitting__c,  Kitting__r.Name,  
	            SGST_Amount__c,  SGST__c,  Total_Amount__c FROM Invoice_Line_Item__c where Invoice__c=:inId];

	}

}