BARC UAT/src/objects/Kitting__c.object
<CustomObject>
    <label>Kitting</label>
    <nameField>
        <displayFormat>AC#{00000000}</displayFormat>
        <label>Kitting Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kitting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List__c.object
<CustomObject>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PLN-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Packing List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Kitting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kitting</label>
        <referenceTo>Kitting__c</referenceTo>
        <relationshipLabel>Packing List Line Items</relationshipLabel>
        <relationshipName>Packing_List_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packing_List__c</fullName>
        <label>Packing List</label>
        <referenceTo>Packing_List__c</referenceTo>
        <relationshipLabel>Packing List Line Items</relationshipLabel>
        <relationshipName>Packing_List_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Packing List Line Item</label>
    <nameField>
        <displayFormat>PLLI-{0000000}</displayFormat>
        <label>Packing List Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing List Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/classes/AddKittingOnPackListCls.cls
public class AddKittingOnPackListCls {
    
public Id pkid{get; set;}
public Id selectId{get; set;}
public Integer delId{get; set;}
public List<Kitting__c> klist{get; set;}
public List<Packing_List_Line_Item__c> pkline{get; set;}

    public AddKittingOnPackListCls(){
        pkid=ApexPages.currentPage().getParameters().get('id');
        
        klist=[select id, Name from Kitting__c];
        pkline= new List<Packing_List_Line_Item__c>();
        
    }
    
    public void add(){
        
        for(Kitting__c k:[select id, Name from Kitting__c where id=:selectId]){
            
            Packing_List_Line_Item__c p = new Packing_List_Line_Item__c();
            p.Packing_List__c=pkid;
            p.Kitting__c=k.id;
            pkline.add(p);
        }
        
    }
    
    public void rem(){
        
        pkline.remove(delId);   
    }
    
    public PageReference Save(){
        
        insert pkline;
        
        PageReference pg = new PageReference('/'+pkid);
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference cancel(){
        
        PageReference pg = new PageReference('/'+pkid);
        pg.setRedirect(true);
        return pg;    
        
    }

}