BARC UAT/src/objects/Packing_List__c.object
<CustomObject>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PLN-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Packing List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Packing_List_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Packing_List__c</fullName>
        <label>Packing List</label>
        <referenceTo>Packing_List__c</referenceTo>
        <relationshipLabel>Packing List Line Items</relationshipLabel>
        <relationshipName>Packing_List_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Packing List Line Item</label>
    <nameField>
        <displayFormat>PLLI-{0000000}</displayFormat>
        <label>Packing List Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing List Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/classes/GenarateDeliveryChallanTest.cls
@isTest
public class GenarateDeliveryChallanTest {

	public static testMethod void test() {
	    
	    Packing_List__c pk = new Packing_List__c();
	    insert pk;
	    
	    Packing_List_Line_Item__c pkl = new Packing_List_Line_Item__c(Packing_List__c=pk.id);
	    insert pkl;
	    
	    ApexPages.currentPage().getParameters().put('id', pk.id);
	    
	    GenarateDeliveryChallan gdc = new GenarateDeliveryChallan();
	    gdc.generate();

	}

}