BARC UAT/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Current_House_Ownership_status__c</fullName>
        <label>Current House Ownership status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ownership</fullName>
                </value>
                <value>
                    <fullName>Rented</fullName>
                </value>
                <value>
                    <fullName>Provided by Employer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Durables_in_working_condition__c</fullName>
        <inlineHelpText>Please select the durables which are in working condition, at your residence (Select Multiple option)</inlineHelpText>
        <label>Durables in working condition</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Air Conditioner</fullName>
                </value>
                <value>
                    <fullName>Car / Jeep / Van</fullName>
                </value>
                <value>
                    <fullName>Celling Fan</fullName>
                </value>
                <value>
                    <fullName>Color Tv</fullName>
                </value>
                <value>
                    <fullName>LPG Stove</fullName>
                </value>
                <value>
                    <fullName>Personal Computer/ Laptop</fullName>
                </value>
                <value>
                    <fullName>Refrigerator</fullName>
                </value>
                <value>
                    <fullName>Two-Wheeler</fullName>
                </value>
                <value>
                    <fullName>Washing Machine</fullName>
                </value>
                <value>
                    <fullName>Does the Chief wage earner (contributes the most to household expenditure) of the Household own any agricultural land?</fullName>
                </value>
                <value>
                    <fullName>Car/Jeep/Van</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household_StatusN__c</fullName>
        <label>Household Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agreed Scheduled</fullName>
                </value>
                <value>
                    <fullName>Next Call</fullName>
                </value>
                <value>
                    <fullName>Not Connected</fullName>
                </value>
                <value>
                    <fullName>Installed agree</fullName>
                </value>
                <value>
                    <fullName>Next Visit</fullName>
                </value>
                <value>
                    <fullName>Door Locked</fullName>
                </value>
                <value>
                    <fullName>Refuse</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Technical Issue</fullName>
                </value>
                <value>
                    <fullName>Dongle Not Working</fullName>
                </value>
                <value>
                    <fullName>STB Not Working</fullName>
                </value>
                <value>
                    <fullName>Home Not Found</fullName>
                </value>
                <value>
                    <fullName>FORWARDED</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BARC UAT/src/objects/Survey_Member__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age (Completed Years)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_House_Ownership_status__c</fullName>
        <inlineHelpText>What best describes the ownership of this house?</inlineHelpText>
        <label>Current House Ownership status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ownership</fullName>
                </value>
                <value>
                    <fullName>Rented</fullName>
                </value>
                <value>
                    <fullName>Provided by Employer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Member</relationshipLabel>
        <relationshipName>Survey_Member</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Member</label>
    <nameField>
        <displayFormat>SM-{0}</displayFormat>
        <label>Survey Member No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Member</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/objects/Survey_TV__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey TV</relationshipLabel>
        <relationshipName>Survey_TV</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey TV</label>
    <nameField>
        <displayFormat>ST-{0}</displayFormat>
        <label>Survey TV No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey TV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BARC UAT/src/classes/CreatehouseholdTest.cls
@isTest
public class CreatehouseholdTest {

	public static testMethod void test() {
	    
	    Survey__c sur = new Survey__c();
	    sur.Current_House_Ownership_status__c='Ownership';
	    insert sur;
	    
	    Survey_TV__c stv = new Survey_TV__c();
	    stv.Survey__c=sur.id;
	    insert stv;
	    
	    Survey_Member__c svm= new Survey_Member__c();
	    svm.Survey__c=sur.id;
	    svm.Age__c='24';
	    insert svm;
	    
	    sur.Household_StatusN__c = 'Installed agree';
	    sur.Durables_in_working_condition__c='Air Conditioner';
	    update sur;
	    

	}

}